### ISSUE TITLE
Link to documentation leads to Not Found 404

### ISSUE THREAD

**Issue by thedrow** [Qiskit/rustworkx#670] opened 2022-08-30 14:47 UTC
https://qiskit.org/documentation/rustworkx/ leads nowhere and the documentation is currently unavailable.

**Comment by IvanIsCoding** [comment] 2022-08-30 20:14
This is a duplicate of #664: `rustworkx` has not been released yet, hence the stable documentation for `rustworkx` is still not up. Once the release is up, the documentation will be up.

If you want to access the dev documentation go to:  https://qiskit.org/documentation/rustworkx/dev. And the documentation under the old name is always available at https://qiskit.org/documentation/retworkx

**Closed by IvanIsCoding** 2022-08-30 20:14 UTC
Labels: bug
