### ISSUE TITLE
Some (or all) algorithms aren't interruptable with Ctrl-C

### ISSUE THREAD

**Issue by yurivict** [Qiskit/rustworkx#953] opened 2023-07-31 18:13 UTC
### Information

- **rustworkx version**: 0.13.0
- **Python version**: 3.9
- **Rust version**:
- **Operating system**: 1.71.0

### What is the current behavior?
Pressing Ctrl-C on long running algorithms doesn't stop them.

### What is the expected behavior?
Ctrl-C should be respected.

### Steps to reproduce the problem
Testcase:
```
import rustworkx as rx

G = rx.directed_gnp_random_graph(1000, 0.5)
rx.all_simple_paths(G, 0, 1, 25, 25)
```

**Comment by IvanIsCoding** [comment] 2023-07-31 22:34
Closing this as a duplicate of #511, (unfortunately) a known issue

**Closed by IvanIsCoding** 2023-07-31 22:34 UTC
Labels: bug
