### ISSUE TITLE
Add an equivalent to networkx's topological_generations?

### ISSUE THREAD

**Issue by dizhouwu** [Qiskit/rustworkx#1014] opened 2023-10-21 16:54 UTC
I find networkx's topological_generations https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.dag.topological_generations.html
to be very friendly for scheduling the parallelized nodes. Is there a plan to add this feature?

Thanks.

**Comment by IvanIsCoding** [comment] 2023-10-21 19:22
This should be possible given we already have the code for topological sort. It wasn’t in the roadmap but seems like a good issue for first time contributors

**Comment by inmzhang** [comment] 2024-01-13 13:15
I can take this one, please assign it to me @IvanIsCoding.

**Closed** 2024-01-15 03:55 UTC
Labels: enhancement, good first issue

**Comment by mnesarco** [comment] 2024-10-18 03:07
Something is not working here:

```python
from typing import Any
import rustworkx as rnx

def test_topological_generations(edges: list[tuple[Any, Any]]):
    g = rnx.PyDiGraph()
    for left, right in edges:
        if left not in g.nodes():
            left_e = g.add_node(left)
        if right not in g.nodes():
            right_e = g.add_node(right)
        g.add_edge(left_e, right_e, None)

    print("nodes = ", g.nodes())

    for layer, nodes in enumerate(rnx.topological_generations(g)):
        print(layer, [g.nodes()[i] for i in nodes])

# Graph:
# 2 --\
#      1 ---> 4 ---> 5
# 3 --/

test_topological_generations([(2, 1), (3, 1), (1, 4), (4, 5)])

# Result (bad):
# nodes =  [2, 1, 3, 4, 5]
# 0 [2, 3]
# 1 [5, 4, 1]

# Expected Result:
# nodes =  [2, 1, 3, 4, 5]
# 0 [2, 3]
# 1 [1]
# 2 [4]
# 3 [5]


```

**Comment by IvanIsCoding** [comment] 2024-10-18 17:06
@mnesarco your graph generation is incorrect. You are mixing node weights (the payload that can be any Python object) with node indices. Node indices are generated by rustworkx and are integers. Here is the fixed version with the correct graph creation:
```
from typing import Any
import rustworkx as rnx

def test_topological_generations(edges: list[tuple[Any, Any]]):
    g = rnx.PyDiGraph()
    g.extend_from_edge_list(edges)
    

    for layer, nodes in enumerate(rnx.topological_generations(g)):
        print(layer, [g.nodes()[i] for i in nodes])

test_topological_generations([(2, 1), (3, 1), (1, 4), (4, 5)])
```

The output is:
```
```

**Comment by IvanIsCoding** [comment] 2024-10-18 17:21
No worries. Sometimes converting code from NetworkX is not 1-to-1, check https://www.rustworkx.org/networkx.html for more tips.

**Comment by mnesarco** [comment] 2024-10-20 00:56
Hi @IvanIsCoding your proposed code does not work as intended, it assumes that nodes and its indices are the same thing but the idea is that `test_topological_generations(edges: list[tuple[Any, Any]])` receive tuples of nodes not tuples of node indices (hence the tuple(Any, Any) type hint)

> ```
> from typing import Any
> import rustworkx as rnx
> 
> def test_topological_generations(edges: list[tuple[Any, Any]]):
>     g = rnx.PyDiGraph()
>     g.extend_from_edge_list(edges)
>     for i in g.node_indices():
>       g[i] = i + 1
>     
> 
>     for layer, nodes in enumerate(rnx.topological_generations(g)):
>         print(layer, [g.nodes()[i] for i in nodes])
> 

Here is an example of the problem:

```python
# A ---\
#       B --- D
# C ---/
test_topological_generations([("A", "B"), ("C", "B"), ("B", "C")])
```

The obvious execution error:

```bash
Traceback (most recent call last):
  File "graph.py", line 49, in <module>
    test_topological_generations([("A", "B"), ("C", "B"), ("B", "C")])
  File "graph.py", line 38, in test_topological_generations
    g.extend_from_edge_list(edges)
TypeError: argument 'edge_list': 'str' object cannot be interpreted as an integer
```

This is the thing i was trying to resolve in my original code.

**Comment by mnesarco** [comment] 2024-10-20 01:35
@IvanIsCoding 
I have found a solution, but I have two questions:

1. Is all this required or is it there a better way?
2. I am moving from networkx because i want better performance, does the cost of node mapping part defeat the purpose of moving?

my current dumb solution:

```python
from typing import Any
import rustworkx as rnx

def node_mapper(edges: list[tuple[Any, Any]], added: dict[Any, int]):
    node_index = 0
    for x,y in edges:
        x_index = added.get(x, None)
        if x_index is None:
            x_index = node_index
            added[x] = node_index
            node_index += 1
        y_index = added.get(y, None)
        if y_index is None:
            y_index = node_index
            added[y] = node_index
            node_index += 1
        yield x_index, y_index

def test_topological_generations(edges: list[tuple[Any, Any]]):
    g = rnx.PyDiGraph()

    mapped_nodes = dict()
    g.extend_from_edge_list(list(node_mapper(edges, mapped_nodes)))

    for node, index in mapped_nodes.items():
        g[index] = node

    for layer, nodes in enumerate(rnx.topological_generations(g)):
        print(layer, [g[i] for i in nodes])

# A ---\
#       B --- D
# C ---/
test_topological_generations([("A", "B"), ("C", "B"), ("B", "D")])

```

Result:

```bash
0 ['A', 'C']
1 ['B']
2 ['D']
```

**Comment by IvanIsCoding** [comment] 2024-10-20 01:38
Again, I recommend you to read the NetworkX -> rustworkx conversion guide. `PyDiGraph.extend_from_edge_list` is a function that takes node indices, not arbitrary objects. Once you know how to build the graphs, you'll finally be able to reap the performance benefits this library was written for.

If you want a general function that works with any Python object:
```
import rustworkx as rx

def test_topological_generations(edges: list):
    g = rx.PyDiGraph()
    node_mapping = {}
    for a, b in edges:
      if a not in node_mapping:
        node_mapping[a] = g.add_node(a)
      if b not in node_mapping:
        node_mapping[b] = g.add_node(b)
      g.add_edge(node_mapping[a], node_mapping[b], None)

    for layer, nodes in enumerate(rx.topological_generations(g)):
        print(layer, [g.nodes()[i] for i in nodes])

test_topological_generations([("A", "B"), ("C", "B"), ("B", "D")])
```

Will print:
```
0 ['A', 'C']
1 ['B']
2 ['D']
```

However, that function does a lot of dictionary lookups that are not necessary. This would be the idiomatic way:
```
import rustworkx as rx

g = rx.PyDiGraph()
node_a = g.add_node("A")
node_b = g.add_node("B")
node_c = g.add_node("C")
node_d = g.add_node("D")
# if you want edge weights use add_edges_from() instead, add_edges_from_no_data is for no weights
g.add_edges_from_no_data([(node_a, node_b), (node_c, node_b), (node_b, node_d)])
for layer, nodes in enumerate(rx.topological_generations(g)):
        print(layer, [g.nodes()[i] for i in nodes])
```

Has the same output from above.

**Comment by mnesarco** [comment] 2024-10-20 01:42
We posted basically the same code at the same time. :D

**Comment by IvanIsCoding** [comment] 2024-10-20 01:43
> [@IvanIsCoding](https://github.com/IvanIsCoding) I have found a solution, but I have two questions:
> 
> 1. Is all this required or is it there a better way?
> 2. I am moving from networkx because i want better performance, does the cost of node mapping part defeat the purpose of moving?
> 

1. I posted a slightly simpler solution but in short yes, dealing with the indices is required
2. In general it is going to be about the same or faster. But the thing about using dictionaries, your code will spend more time looking up values than rustworkx doing computations. I wouldn't be surprised that `rx.topological_generations` takes a fraction of the time of doing that original Python for loop.

**Comment by mnesarco** [comment] 2024-10-20 01:46
Yes you are right, but there is no option, the edges came from ids in a large database, and i need topological_generations of the ids in the database.

**Comment by IvanIsCoding** [comment] 2024-10-20 01:47
In your case I'd benchmark it. A good example of when it is worth it is this [Thesis from J. Vaule](https://www.duo.uio.no/handle/10852/112536). The author did `networkx -> rustworkx -> networkx` conversions for computation and despite converting from and back was still faster than the original

**Comment by mnesarco** [comment] 2024-10-20 01:49
That sounds interesting, i will check. Thank you very much.

**Comment by mnesarco** [comment] 2024-10-20 03:16
Amazing !!! this is my benchmark comparing vanilla networkx code againsts equivalent rustworkx code including node mappings.

Average case:

```bash
directed_barabasi_albert_graph(n=10000, m=100)
timeit(..., number=10)
  networkx...:  11.591704827000058 (100.0000%)
  rustworkx..:  4.427363180000043 (38.1942%)
  saved......:  7.164341647000015 (61.8058%)
```

Small case:

```bash
directed_barabasi_albert_graph(n=1000, m=100)
timeit(..., number=10)
  networkx...:  0.8124548499999946 (100.0000%)
  rustworkx..:  0.3219222070000569 (39.6234%)
  saved......:  0.4905326429999377 (60.3766%)
```

The move is totally worth.
